// TODO: peep listen, diff.resize

var diff = require('ansi-diff')({ width: process.stdout.columns })

var argv = require('minimist')(process.argv.slice(2))

var HELP = 'Usage: peep replay FILE | peep listen [PORT] [FILE]\n\n' +
 'FILE: special PEEP file generated by a Peep instance\n' +
 'PORT: listen on this PORT and redirect inbound data to FILE\n\n' +
 'If your debugging with Peep instances in a browser you need\n' +
 'to first spin up a teeing server with "peep listen" since one cannot\n' +
 'write a PEEP file from a browser context.'

var BUF419 = Buffer.from([ 0, 4, 1, 9, 4, 1, 9, 0 ])

function datify (timestamp) {
  var date = new Date(timestamp)
  var millis = date.getMilliseconds()
  return date.toString().slice(0, 24) + '.' + millis
}

function spacify (hexs) {
  for (var s = '', i = 0; i < hexs.length; i++) {
    if (i % 2 === 0 && i !== 0) s += ' '
    s += hexs[i]
  }
  return s
}

function ondata (pac) {
  process.stdout.write(diff.update(
    'datetime: ' + datify(pac.timestamp) + '\n' +
    'chunk: ' + spacify(pac.chunk.toString('hex')) + '\n'
  ))
}

function replay (file) {
  createPeepReadStream(file)
    .on('data', ondata)
    .on('error', console.error)
}

function listen (port, file) {

}
